### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by denyskonakhevych** [denyskonakhevych/SubwayTurnstile#1]
Dear Andrii,

Please, except my apologies for such a great violation of the terms. Please provide your feadback for current task.

Many thanks!

**Comment by arodionov** [comment]
- Класс Tourniquet не должен хранить в себе информацию о поездках (задача турникета пропустить или не пропустить)
- Так же private class Passage объявлен неправильно
- В enum PassType неправильно перемешивать все типы. Там же загадочно выглядит конструктор PassType(Integer... value)
- Для class DatePass так же есть ограничение на количество дней
- Пакет tests не должен находиться в основном дереве кода, и все внешние зависимости в тестах должны мокаться

**Comment by denyskonakhevych** [comment]
Класс Tourniquet больше не хранит в себе информацию о поездках, этот функционал перенесен в Server.
PassType разнесен на несколько других Enum-ов.
Тесты исправлены и теперь mock-аются.

Проверте, пожалуйста, текущую реализацию
